version: 2
jobs:
  build:
    working_directory: ~/ff1randomizer
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout

      - run:
          name: compile
          command: |
            cd FF1RandomizerOnline && \
            dotnet publish -c Debug

      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: docker
          command: |
            cd FF1RandomizerOnline && \
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS && \
              docker build -t entroper/finalfantasyrandomizer:beta -f Dockerfile.beta . && \
              docker push entroper/finalfantasyrandomizer:beta
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS && \
              docker build -t entroper/finalfantasyrandomizer:latest -f Dockerfile . && \
              docker push entroper/finalfantasyrandomizer:latest
            fi
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdir -p ~/.ssh && \
              cp .ssh/known_hosts ~/.ssh/known_hosts && \
              ssh circle@finalfantasyrandomizer.com "./deployff1r.sh $CIRCLE_BRANCH"
            fi
